// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/list-projects.ts
import { createClient } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.23.8";
var list_projects_default = defineTool({
  name: "list_projects",
  title: "List projects",
  description: "List published Where2Studios portfolio projects. Optionally filter by category or featured flag.",
  inputSchema: {
    category: z.string().optional().describe("Filter by category (e.g. 'corporate', 'social', 'brand')."),
    featured: z.boolean().optional().describe("If true, return only featured projects."),
    limit: z.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ category, featured, limit }) => {
    const supabase = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    let q = supabase.from("projects").select("id, slug, title, category, client_name, description, thumbnail_url, video_url, featured, display_order").eq("published", true).order("display_order", { ascending: true }).limit(limit ?? 20);
    if (category) q = q.eq("category", category);
    if (featured !== void 0) q = q.eq("featured", featured);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { projects: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-project.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.23.8";
var get_project_default = defineTool2({
  name: "get_project",
  title: "Get project",
  description: "Fetch a full published Where2Studios project (case study) by its slug.",
  inputSchema: {
    slug: z2.string().min(1).describe("Project slug, e.g. 'linkedin-feature'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ slug }) => {
    const supabase = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("projects").select("*").eq("slug", slug).eq("published", true).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: `No published project with slug '${slug}'.` }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { project: data }
    };
  }
});

// src/lib/mcp/tools/list-testimonials.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.23.8";
var list_testimonials_default = defineTool3({
  name: "list_testimonials",
  title: "List testimonials",
  description: "List published Where2Studios client testimonials.",
  inputSchema: {
    limit: z3.number().int().min(1).max(50).optional().describe("Max rows to return (default 20).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const supabase = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await supabase.from("testimonials").select("id, name, role, company, quote, headshot_url, display_order").eq("published", true).order("display_order", { ascending: true }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { testimonials: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/submit-inquiry.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.93.3";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.23.8";
var submit_inquiry_default = defineTool4({
  name: "submit_inquiry",
  title: "Submit contact inquiry",
  description: "Submit a new contact / partnership inquiry to Where2Studios. Use for prospective clients, collabs, or Where2Boys partnerships.",
  inputSchema: {
    name: z4.string().min(1).describe("Full name of the requester."),
    email: z4.string().email().describe("Contact email."),
    company: z4.string().optional().describe("Company or Instagram handle."),
    message: z4.string().min(1).describe("What they want to work on."),
    collab_type: z4.string().optional().describe("Type of collab, e.g. 'Brand partnership', 'Event coverage'."),
    timeline: z4.string().optional().describe("Requested timeline, e.g. 'ASAP', 'Next month'."),
    budget_range: z4.string().optional().describe("Budget range, e.g. '$3K to $5K'."),
    source: z4.enum(["mcp", "where2boys", "website"]).optional().describe("Source tag (default 'mcp').")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async (input) => {
    const supabase = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const payload = { ...input, source: input.source ?? "mcp" };
    const { data, error } = await supabase.from("contact_submissions").insert(payload).select("id, created_at").maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Inquiry received (id: ${data?.id}). The team will follow up by email.` }],
      structuredContent: { submission: data }
    };
  }
});

// src/lib/mcp/index.ts
var mcp_default = defineMcp({
  name: "where2studios-mcp",
  title: "Where2Studios",
  version: "0.1.0",
  instructions: "Tools for Where2Studios, a creative production studio and the Where2Boys creator brand. Use `list_projects` and `get_project` to browse the portfolio, `list_testimonials` for client quotes, and `submit_inquiry` to send a new partnership or contact request.",
  tools: [list_projects_default, get_project_default, list_testimonials_default, submit_inquiry_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
